# deploy/charts/nutrition-tracker/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nutrition-tracker.fullname" . }}-secret
  labels:
    {{- include "nutrition-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  api-keys: {{ .Values.secrets.apiKeys | b64enc | quote }}
  usda-api-key: {{ .Values.secrets.usdaApiKey | b64enc | quote }}